### ISSUE TITLE
Allow loading tapes by query

### ISSUE THREAD

**Issue by libitx** [operate-bsv/op_agent#2]
Currently tapes can only be loaded one-by-one from a given txid. It would be useful to be able to load one or more tapes from a query. The `Operate.Adapter` behaviour should expect a common API, but it should be up to the adapter to decide how to implement the query. Obviously not all adapters will support a bitdb query and other adapters may have their own unique way of querying.

### Top level

The `Operate` module should offer `load_tapes_by/2` and `load_tapes_by!/2` functions that accept a `map` query arg and a `keyword` options arg. An array of `Operate.Tape.t` structs should be returned.

Eg:

```elixir
qry = %{
  "out.tape.cell" => %{
    "$elemMatch" => %{
      "i" => 0,
      "s" => "1PuQa7K62MiKCtssSLKy1kh56WWU7MtUR5"
    }
  }
}

{:ok, tapes} = Operate.load_tapes_by(qry)
```

### Adapter behaviour

The `Operate.Adapter` module should provide the callback `fetch_tx_by/2` thats accepts a `map` query arg and a `keyword` options arg and return an array of `Operate.BPU.Transaction.t` structs. An adapter can chose not to implement the callback if it doesn't make sense to do so.

Eg:

```elixir
{:ok, txns} = Operate.fetch_tx_by(qry)
```

### Agent extension

The `Operate.VM.Extension.Agent` module should provide extensions for loading/executing tapes in different ways. The exact api needs some thought, but as by default the same adapter will be used as per the configuration, it will be necessary to allow explicit setting of the adapter from within Lua.

Eg:

```lua
-- Lua code, used in Ops
local opts = {
  tape_adapter = {
    'Operate.Adapter.Bob',
    {some = 'config'}
  }
}
agent.exec(txid, opts)

-- and by query
local qry = {}
qry['out.tape.cell'] = {}
qry['out.tape.cell']['$elemMatch'] = {
  i = 0,
  s = '1PuQa7K62MiKCtssSLKy1kh56WWU7MtUR5'
}
agent.exec_by(qry, opts)
```

**Comment by MerlinB** [comment]
Another related extension to consider is to allow queries that return multiple results. An example usecase would be a protocol that considers a subset or all of a nodes existing child nodes to be part of the same object.

**Comment by libitx** [comment]
The latest commit adds some new functions to the agent extension. The API now mirrors the top-level `Operate` module:

```lua
-- Loads a tape by txid. Returns a tape serialised into a lua table
tape = agent.load_tape(txid)

-- Loads a list of tapes by a custom query. Returns all tapes in a integer indexed table 
query = { find = {}, limit = 5 }
query.find['out.tape.cell'] = {}
query.find['out.tape.cell']['$elemMatch'] = {
  i = 0,
  s = '1PuQa7K62MiKCtssSLKy1kh56WWU7MtUR5'
}
tapes = agent.load_tapes_by(query)

-- Runs the given tape and returns the result
result = agent.run_tape(tape)

-- All of the above functions can optionally be passed a second parameter to override Operates configuration options
```
